parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Controller'

    App\Service\JwtService:
        arguments:
            $jwtPrivateKeyPath: '%kernel.project_dir%/config/jwt/private.pem'
